name: Build and publish docker image

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  build-publish-docker-image:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    permissions:
      contents: read      # Required for reading the repository contents
      packages: write     # Required for pushing to GitHub Packages
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short Git SHA
        id: vars
        run: echo "sha=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build the docker image
        run: |
          docker build -f Dockerfile-prod --build-arg VITE_VIEW_ROOT_URL=https://view.cloud.open-dpp.de --build-arg VITE_ADMIN_ROOT=https://admin.cloud.open-dpp.de --build-arg VITE_KEYCLOAK_ROOT=https://auth.cloud.open-dpp.de --build-arg VITE_API_ROOT=https://api.cloud.open-dpp.de . -t ghcr.io/${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:${{ env.sha }}

      - name: Push the docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ env.sha }}



